### ISSUE TITLE
Add an option to pass the offset for the date in the add_partitions method

### ISSUE THREAD

**Issue by bharthur** [ankane/pgslice#11]
https://github.com/ankane/pgslice/blob/f935dc6dc5c17a69d6c4028ddc5b85d69dfe9cdc/lib/pgslice.rb#L165

I came across an issue when trying to add the future partitions a few days after I made the initial partition. And it started throwing the error: `relation "public.table_name_<today's_date>" does not exist (PG::UndefinedTable)`. I fixed it by changing the hardcoded offset.  But it would be great if you could provide an option to pass the offset or date itself. Thanks for writing this awesome library BTW!!!

**Comment by ankane** [comment]
Hey @bharthur, thanks for the report 👍 It now finds the latest partition instead of hard-coding todays.

**Comment by bharthur** [comment]
@ankane awesome thanks!
