### ISSUE TITLE
Table not found when table is present in the schema,

### ISSUE THREAD

**Issue by kamaljha** [ankane/pgslice#12]
Steps to reproduce.
1)created request table in the database BIDA. 
2)Imported data on the table.
3)Set the connection url as below:
set PGSLICE_URL=postgres://<USERNAME>:<PASSWORD>@localhost/BIDA
4)running pgslice to create prep .
c:\Program Files\PostgreSQL\10\bin>pgslice prep "hotwire"."request" create_date month --dry-run
Table not found: hotwire.request
c:\Program Files\PostgreSQL\10\bin>pgslice prep request create_date month
Table not found: request
5)BIDA=# select count(*) from hotwire.request;
  count
---------
 6710826
(1 row)

**Comment by ankane** [comment]
Hey @kamaljha, thanks for reporting 👍 Schema support is improved on the `master` branch. You should be able to do:

```sh
gem install specific_install
gem specific_install https://github.com/ankane/pgslice.git
pgslice prep hotwire.request create_date month
```
