### ISSUE TITLE
When primary key is a composite key partition table is having only one key as primary key.

### ISSUE THREAD

**Issue by kamaljha** [ankane/pgslice#13]
1) Steps to reproduce.:
Parent table defination : 
request
(
    message_id character varying(42) COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp without time zone,
    state character varying(18) COLLATE pg_catalog."default",
    err_msg character varying(1000) COLLATE pg_catalog."default",
    err_code character varying(3) COLLATE pg_catalog."default",
    campaign character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT request_campaign_id PRIMARY KEY (message_id, campaign)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

2) pgslice prep hotwire.request created_date month

3) pgslice add_partitions hotwire.request --intermediate --past 60 --future 60

4)pgslice fill public.request --batch-size 50000
Insert failed due to duplicate entry.

5) Child table defination
CREATE TABLE hotwire.request_201304
(
    message_id ,
    created_date ,
    state ,
    err_msg ,
    err_code ,
    campaign ,
    CONSTRAINT request_201304_pkey PRIMARY KEY (message_id),  ->> this is the issue.
    CONSTRAINT request_201304_created_date_check CHECK (created_date >= '2013-04-01'::date AND created_date < '2013-05-01'::date)
)
    INHERITS (hotwire.request_intermediate)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

Thanks
Kamal

**Comment by ankane** [comment]
Hey @kamaljha, thanks for the detailed report 💯 This is fixed on master.
