### ISSUE TITLE
bad URI(is not URI?)

### ISSUE THREAD

**Issue by checkraiser** [ankane/pgslice#15]
I'm setting `PGSLICE_URL` as 
`postgres://user:password@localhost:5432/database`

But when running command 
`pgslice prep table_name column_name period`
i got error: 
```
 bad URI(is not URI?): postgres://user:password@localhost:5432/dbcounter2 (URI::InvalidURIError)
```

How to fix it ?

**Comment by ankane** [comment]
Make sure there are no spaces or special characters in the URL. If your password contains non-URL safe characters, be sure to use percent-encoding to encode them.
