### ISSUE TITLE
PG::Connection injection support

### ISSUE THREAD

**Issue by andrew-newell** [ankane/pgslice#20]
First of all, thank you for building such a helpful tool!

I'm curious if you know of a way that I could initialize a Pgslice instance with an already existing PG::Connection object. I feel like I'm missing something obvious but if not, would you have a preference on how this functionality is added? Assuming you're on board with the idea, of course.

For some context, I have a database in Amazon RDS that I'm going to maintain via a Sidekiq worker (cron is not a viable solution here) and I'd much rather let Pgslice access my PG::Connection from ActiveRecord instead of shelling out and back, it feels very hacky.

**Comment by ankane** [comment]
Hey @andrew-newell, pgslice is designed to be used as a command-line tool, so don't want the added overhead of maintaining a Ruby API.

**Comment by scytherswings** [comment]
@ankane I understand completely. I went ahead and created a gem that wraps and extends the functionality of pgslice with a Ruby API. It's a bit hacky but I have a few projects lined up to use this. Here's a link to the project https://github.com/IlluminusLimited/pgdice

Thanks again for making such an awesome gem!
