### ISSUE TITLE
Postgres 11 default partition and other improvements

### ISSUE THREAD

**Issue by iMobs** [ankane/pgslice#21]
With Postgres 11 on the horizon, I was wondering if there were plans to incorporate some of the improvements being made to partitions? One of the big ones that I'm looking forward to is the ability to set a default partition, which is great for cases like if there was a huge spike in activity and you only want to start partitioning since that point in time. I think it would be great if there was a flag in the prep step to allow for specifying I want to have a catchall, then afterwards partition based on a certain time period.

Another big change is how indexes and foreign keys will be inherited, which I believe will mean that the add_partitions step will not need to set them up.

**Comment by ankane** [comment]
Hey @iMobs, inherited indexes were added in 0.4.2. There haven't been any changes for foreign key inheritance, but will see if this needs to be done when Postgres 11 rc1 is released.

There aren't any plans to enable partitioning after a specific time, but it's an interesting idea. I think this also possible in Postgres 9 and 10, but hesitant to add another partitioning pattern as it increases complexity.

**Comment by ankane** [comment]
Just added foreign key inheritance, and will push out a new release later today.

**Comment by trietphm** [comment]
Hi @ankane, any plan to support the DEFAULT partition?

**Comment by ankane** [comment]
@trietphm No, it doesn't really fit in with the project design.

**Comment by trietphm** [comment]
Thank you for the confirmation. I will update my script and handle the default partition myself then.
