### ISSUE TITLE
Auto-copying foreign key constraint triggers

### ISSUE THREAD

**Issue by lancedikson** [ankane/pgslice#23]
Hi, thanks for the great tool. I was struggling with having a foreign key constraint on the partitioned tables. I think you know what exactly I mean, so I wouldn't explain all the constraints with that mechanism here to make it short, but I can if it's needed.
So, I came up with having a trigger on each partition, which takes a look on the related table with the key, and checks if there is such a record. The only thing here is that I need to remember to apply that trigger to each new partition after creating them. It's not that hard, but something that might be automated with pgslice. But, I'm wondering is it really a good practice to have such triggers...
Anyways, as I see it, it might be a config file or a param for the beginning with the names of triggers that must be copied from the master table to a partition during `pgslice add_partitions`. What do you think about this?
Here is an example of the trigger I want to be applied to the new partitions:
```sql
CREATE OR REPLACE FUNCTION foreign_key_constraint_trigger() RETURNS TRIGGER AS $$
	BEGIN
		PERFORM 1 FROM page_view WHERE id=NEW."impressionId" LIMIT 1;
		IF NOT FOUND THEN
      	RAISE EXCEPTION 'not found page_view record with id=%', NEW."impressionId"; 
			RETURN NULL;
		END IF;
		RETURN NEW;
	END;
$$ LANGUAGE plpgsql;
```
And it doesn't work if I put it just on the master table, it doesn't react on insert.

**Comment by ankane** [comment]
Hey @lancedikson, thanks for sharing. I haven't used foreign keys on partitioned tables in a production setting, so I'm not really sure about best practices. The good news is Postgres 11 supports them natively, so it won't be an issue in the future. I think it's probably best just to create a custom script to run after `add_partitions` in the meantime.

**Comment by lancedikson** [comment]
Ok, thanks for your answer 👍
