### ISSUE TITLE
Support for DATABASE_URL env var?

### ISSUE THREAD

**Issue by EdgarOrtegaRamirez** [ankane/pgslice#25]
Hey! Any plan on supporting the `DATABASE_URL` env var Rails uses by default?

**Comment by ankane** [comment]
Hey @EdgarOrtegaRamirez, pgslice isn't Rails-specific, so no plans to support another environment variable. You can always do:

```sh
export PGSLICE_URL=$DATABASE_URL
```

**Comment by EdgarOrtegaRamirez** [comment]
Thanks for your answer @ankane, I'm planning on using this after migration to PG11 is done.

thank you for this gem
