### ISSUE TITLE
Upgrading PG 10 to 11+ with partitioned tables from pgslice < 0.4.5  causes duplicate indexes

### ISSUE THREAD

**Issue by andrew-newell** [ankane/pgslice#28]
Scenario: Do a full pgslice partitioning while running PG 10 then upgrade to PG 11+. Every time `add_new_partitions` is called it will add duplicate indexes. 

After looking in the code it looks like the behavior is controlled by a comment on the parent table. Unless I missed something I don't believe the version is checked after tables have been partitioned. This means that when the comment on the table is read it is either missing the version or has the wrong one and thus pgslice creates the partitions as duplicates.

I believe the fix would be to check the version before adding partitions and update the comment if it has changed which should cause pgslice's behavior to adjust accordingly.

OTOH it's not hard to rectify manually if you just update the comment yourself. I was able to fix it by running: (the fix was to add `,version:3` in case other users have run into this)

```sql
COMMENT ON TABLE public.test_execution_logs IS 'column:created_at,period:day,cast:date,version:3';
```

Which fixed the behavior for me.

**Comment by ankane** [comment]
Hey @andrew-newell, thanks for reporting 👍 I'm not sure I understand what's going on. The difference between versions 2 and 3 are that indexes are on the parent table in 3 vs the partitions in 2, and the location of indexes shouldn't change when upgrading from PG 10 to 11.

Can you provide the indexes on the parent table and child tables when:

1. On PG 10
2. After upgrading to PG 11
3. After running `add_partitions` on PG 11

And the output of the `add_partitions` command?

**Comment by andrew-newell** [comment]
Ahh okay this is weird. So I changed my approach to using docker to get a pg10 db and then ran through the steps that my production server had done to it. Pgslice correctly set `version:2` while on pg10 after running `prep` and `add_partitions` which is the expected behaivor.

My issue was worded poorly. I suppose it should have been along the lines of "Somehow the version was missing in the comment on the parent table and after upgrading to pg11 this resulted in duplicate indexes."

After doing more digging I think I know what happened. The commit https://github.com/ankane/pgslice/commit/0527f84e3bb359a8ba5916b81137600dbae7a633 added the behavior for `trigger` vs `declarative` versioning in the table comment but I had partitioned this table __before__ (this is key) that functionality was added.

The code was still able to detect declarative vs trigger partitioning but once I upgraded to pg11 the code from `add_partitions.rb`:

```ruby
      if version < 3
        index_defs = schema_table.index_defs
        fk_defs = schema_table.foreign_keys
      else
        index_defs = []
        fk_defs = []
      end
```
would always run as version `2` without the comment being present which resulted in duplicate indexes due to the code in `table.rb`:
```ruby
      version ||= trigger_comment ? 1 : 2
      declarative = version > 1
```

So to summarize, the table I have in production was partitioned __before__ `version` was part of the table comment. This meant that pgslice was always dynamically detecting the version every time I added partitions which meant it was defaulting to version 2. This was fine until I upgraded to postgres 11, once this happened the creation of indexes should have been stopped but as far as I can tell that is entirely dependent on the presence of `version:3` in the parent table comment which was never there for this particular table.

Some potential solutions:
1. Always update the parent table comment every time partitions are added
2. Add a "doctor" argument to the CLI which would let users double-check that everything is configured correctly.
3. Add a warning/blurb to the README for users who partitioned tables before version `0.4.5` about this behavior.

Thanks for your time with this! I'm happy to help in whatever way I can.

**Comment by ankane** [comment]
Thanks for the additional details. I'm not sure about the proposed solutions. Version 2 seems correct in that situation (whether in the comment or determined dynamically). This indicates the parent table does not have indexes, which is correct for tables that are upgraded from PG 10 -> 11. We still need to index creation to take place for these tables.

Did you by any chance add the same indexes to the parent table? (this may explain the duplicates)

**Comment by andrew-newell** [comment]
Ahhhh, yes. That is what happened. So PG10 partitioning as normal. Then when I migrated to PG11 I changed my structure from a polymorphic relationship to just a simple foreign key. In that same migration I added a foreign key constraint since PG11 allows that on partitioned tables and also added an index on that column to the parent table! That's exactly what happened :D

**Comment by andrew-newell** [comment]
After closer inspection my "fix" isn't exactly the best course of action, as you have hinted at. Some of the indexes are now missing on the new partitions since they were already on the parent table before the migration. Do you have any thoughts on the best way to rectify this? I can't keep creating duplicate indexes, but I also can't allow new partitions to be missing indexes either. Hmmm..

**Comment by ankane** [comment]
You should be able to fix by changing the version back to 2 and deleting any indexes on the last partition (furthest in future) you've moved to the parent table.

**Comment by andrew-newell** [comment]
Ahh. I'm going the other direction which includes a bit of table locking. I'm going through and adding all the indexes to the partitions and then after all of that adding the index to the parent table. That way all my indexes will be managed by postgres automatically. So far my production database clone has been successful with this change and I think it'll be simpler for maintenance in the long run. Thanks for your help!
