### ISSUE TITLE
RFC: warn on prep if table has 'BEFORE / FOR EACH' triggers

### ISSUE THREAD

**Issue by bf4** [ankane/pgslice#35]
We just used pgslice to partition our tables (pg 11, on heroku) and are very happy.

I was surprised to notice that our triggers weren't firing.  I checked and saw that three triggered functions which had been on the target table were 'orphaned'.

I was able to restore two of them as-is, both were 'AFTER INSERT , FOR EACH'. 

The third one errors when I tried to apply it

```sql
CREATE TRIGGER trigger_update_device_location_events_event_geometry
  BEFORE INSERT OR UPDATE
  ON public.device_location_events
  FOR EACH ROW
  WHEN (((NEW.event_latitude IS NOT NULL) AND (NEW.event_longitude IS NOT NULL)))
  EXECUTE PROCEDURE public.update_device_location_event_event_geometry();
```

with

```
"#<ActiveRecord::StatementInvalid: PG::WrongObjectType: ERROR:  \"device_location_events\" is a partitioned table\nDETAIL:  Partitioned tables cannot have BEFORE / FOR EACH ROW triggers.\n>"
```

The trigger function itself is basically `event_geometry = public.ST_PointFromText('POINT(' || event_longitude::text || ' ' || event_latitude::text || ')', 4326)`

We haven't yet figured out how to restore the trigger in a way that works for the partitioned tables, whether we want to add it to each partitioned table or if we should write it to work slightly differently. I'll update on that point once we do.

Fortunately, for internal reasons, the impact of this is low, but would be good to discover it before going to prod.

**Comment by ankane** [comment]
Hey @bf4, thanks for sharing. I've added a note to the readme. A warning in the prep command makes sense if you want to submit a PR. I think it could warn for any triggers (that they need to be manually added) as well as `BEFORE / FOR EACH ROW` ones.

It also seems like pgslice could set them up on the intermediate table automatically at some point.

**Comment by bf4** [comment]
I'm interested in making a PR but not planning to work on it for at least a few days 

here's what I ended up doing for the trigger

```diff
- CREATE TRIGGER trigger_update_device_location_events_event_geometry BEFORE INSERT OR UPDATE ON public.device_location_events FOR EACH ROW WHEN (((new.event_latitude IS NOT NULL) AND (new.event_longitude IS NOT NULL))) EXECUTE PROCEDURE public.update_device_location_event_event_geometry();
+ CREATE TRIGGER trigger_update_device_location_events_event_geometry AFTER INSERT OR UPDATE ON public.device_location_events FOR EACH ROW WHEN (((new.event_latitude IS NOT NULL) AND (new.event_longitude IS NOT NULL))) EXECUTE PROCEDURE public.update_device_location_event_event_geometry();
```

and for the function

```diff
CREATE FUNCTION public.update_device_location_event_event_geometry() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
+ DECLARE
+   fn_event_geometry public.geometry;
BEGIN
-  NEW.event_geometry = public.ST_PointFromText('POINT(' || NEW.event_longitude::text || ' ' || NEW.event_latitude::text || ')', 4326);
+  IF NEW.event_latitude IS NOT NULL AND NEW.event_longitude IS NOT NULL THEN
+    fn_event_geometry = public.ST_PointFromText('POINT(' || NEW.event_longitude::text || ' ' || NEW.event_latitude::text || ')', 4326);
+    IF NEW.event_geometry IS NULL OR public.ST_Equals(NEW.event_geometry, fn_event_geometry) = false THEN
+      NEW.event_geometry = fn_event_geometry;
+      UPDATE device_location_events
+      SET event_geometry = fn_event_geometry
+      WHERE id = NEW.id;
+    END IF;
+  END IF;
  RETURN NEW;
END;
$$;
```

and my migration was

```ruby
    trigger_name = "trigger_update_device_location_events_event_geometry"
    table_name = "device_location_events"
    function_name = :update_device_location_event_event_geometry
    reversible do |dir|
      dir.up do
        # disabling the trigger first so I think we don't need to lock the table
        execute "ALTER TABLE #{table_name} DISABLE TRIGGER #{trigger_name}"
        drop_trigger trigger_name, on: table_name
        create_function function_name, version: 2
        create_trigger trigger_name, on: table_name, version: 2
      end
      dir.down do  
....
```

though the disable trigger failed on heroku iirc and I had to run the migration manually

**Comment by ankane** [comment]
Thanks for sharing @bf4! Cleaning up issues, but the PR comments still stand.
