### ISSUE TITLE
support non-numeric id in pgslice fill

### ISSUE THREAD

**Issue by singals** [ankane/pgslice#38]
First of all, I love the project and have been using this for quite some time. For me, the most common use case is to partition a table with a numeric id. But this time I want to partition a table that has a varchar type id.
>pgslice fill table_name --batch-size 20000
INSERT INTO "public"."table_name_intermediate" ("id",.......) SELECT "id", ....... WHERE "id" > 11674306 AND "id" <= 11694306 AND "start_time" >= ........................................
PG::UndefinedFunction: ERROR:  operator does not exist: character varying > integer
LINE 4:     WHERE "id_" > 11674306 AND "id_" <= 11694306 AND "start_...

**Comment by ankane** [comment]
Hey @singals, thanks for the suggestion. I don't think it's common enough to support, but you could write a custom script that handles it. If you do, would be great to share it for others who might need it.
