### ISSUE TITLE
`pg` gem `1.3.x` connection string error

### ISSUE THREAD

**Issue by benschwarz** [ankane/pgslice#40]
After updating `pg` gem to the `1.3.x` series, `pgslice` errors and exits on what (I guess?) to be a connection string issue

Example command using `pg` versions `1.3.0` ⇢ `1.3.3`: 

```
$ PGSLICE_URL="postgresql://localhost/my_db" bundle exec pgslice prep my_table_name created_at month
missing key/value separator "=" in URI query parameter: ""
```

With `pg` version `1.2.3` (most recent of `1.2.x` series) `pgslice` is able to connect and run: 

```
$ PGSLICE_URL="postgresql://localhost/my_db" bundle exec pgslice prep my_table_name created_at month

BEGIN;

CREATE TABLE "public"."my_table_name" (LIKE "public"."my_table_name" INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING STORAGE INCLUDING COMMENTS) PARTITION BY RANGE ("created_at");

etc, etc
```

**Comment by ankane** [comment]
Hey @benschwarz, thanks for reporting! Will push a new release shortly.

**Comment by benschwarz** [comment]
Wow, thanks for the speedy reply and fix @ankane 🤝
