### ISSUE TITLE
Missing Updates while filling?

### ISSUE THREAD

**Issue by andyatkinson** [ankane/pgslice#48]
I presented our pgslice based solution today and an astute listener correctly pointed out we might be missing updates to rows that were updated after they were filled, but before the fill was done. 😢 

For our biggest table the duration of the "fill" was very long, 8 hours, so I was thinking I could check our `updated_at` timestamp column since the fill start time and try and identify the `id` of any rows that have been updated. To make that fast, possibly a partial index that's only when `updated_at` is set, and possibly based on a certain time.

Then with those `id` values, I could do an `UPDATE` statement. I'm only seeing `INSERT` statements in pgslice. So this updates scenario is not something that's currently supported, correct?

A possible extension or concept to add on to that exists in pgslice is the `--swapped` concept, filling more inserts post "swap" with missing changes from the retired table. That feels similar to catching missed updates. Maybe `--swapped` could include updates, or a separate option `--with-updates` could be added.

Thoughts?

**Comment by ankane** [comment]
Hey @andyatkinson, correct, `fill` is only designed for append-only tables, so it won't capture any updates. There could probably be an option to copy updates as well (or users could create a custom script to do this after running `fill --swapped`).

**Comment by ankane** [comment]
Cleaning up issues (think it's better as a custom script for now, but if someone creates one, please share).
