### ISSUE TITLE
Add support to keep synced both tables

### ISSUE THREAD

**Issue by owen2345** [ankane/pgslice#51]
Could be great to keep synced both tables (optional), like:
- When adding/editing/deleting rows from the new table, then replicate the action in the old table
- Ability to stop/cancel old table syncing (stop doing the above point)

By this way, if something went wrong once the new table was the official one for some time, then rolling back to the old table we get the updated data.

**Comment by ankane** [comment]
Hi @owen2345, thanks for the suggestion. I don't want to add/support the complexity, but maybe someone can create a fork for this.
