### ISSUE TITLE
Week slice option

### ISSUE THREAD

**Issue by Serg0** [ankane/pgslice#55]
Hey @pohodnya, thanks for the PR! The code looks super clean. From my understanding, Postgres can handle thousands of partitions, so I'm not sure an additional period is needed.

_Originally posted by @ankane in https://github.com/ankane/pgslice/issues/36#issuecomment-698768270_

Nevertheless, PG is able to handle thousands of partitions, but there may be issues if you have fewer CPU cores than partitions.
There may be an issue if you need to request  2 weeks of data and the server has let's say only 4 CPU cores.
It is a request to 2 tables vs a request to 14 tables. I believe that one core may do only one table request at a time.
Considering that index time processing is not linear, I suppose that the request to 2 larger tables will be faster than the request to 14 small tables. Therefore the week option may be very helpful.

Just saying.

**Comment by ankane** [comment]
Hi @Serg0, feel free to create a new issue with performance data if you try it.
