### ISSUE TITLE
Index names are not preserved

### ISSUE THREAD

**Issue by afn** [ankane/pgslice#9]
Ideally, the end state of the setup process should result in a parent table that's indistinguishable from the original table other than the presence of child tables and the INSERT trigger. But the way it's currently implemented, the parent table has a primary key and indexes with names based on the intermediate table name. For instance, with a table called `search_results` with an index on `user_id`, we end up with:

```
Indexes:
    "search_results_intermediate_pkey" PRIMARY KEY, btree (id)
    "search_results_intermediate_user_id_idx" btree (user_id)
```

This could be addressed by doing the following:

1. Have `pgslice prep` rename the indexes (including the primary key index) on the original table to be based on the **retired** table name, e.g. `search_results_retired_pkey`, and create indexes on the intermediate table using the original names of the indexes.
2. Have `pgslice unprep` reverse this process (after dropping the intermediate table, rename the indexes on the original table back to their original names).

The only tricky part here is that the unprep operation needs to be able to determine the mapping between index names in the two tables. It could do this based on the index definition, but that might be ambiguous (you could have multiple identical indexes with different names, for instance). Alternatively, we could assume that the order of indexes in `pg_indexes` is stable, but that might be an incorrect assumption. The worst case scenario, then, is that after rolling back with `pgslice unprep`, the original table has some indexes named differently than their original names.

Alternatively, we should introduce a new command, e.g. `pgslice rename_indexes`, to be run after step 8 (right before dropping the retired table), which attempts to rename the indexes on the parent table based on the index names in the retired table. This suffers from the same issue of potential ambiguity, but at least this way, we can inform the user about the ambiguity and let them resolve it on their own.

Let me know what you think -- happy to pitch in with a PR.

Also when #8 is addressed, we should make sure that foreign key names are also preserved.

**Comment by ankane** [comment]
Hey @afn, another good suggestion 👍  I don't think we should touch the original table until after the `swap` command. As you've mentioned above, being able to map indexes will be the tricky part. Before starting on this, I think it'd be good to get an idea of how you plan to approach it so all the edge cases are accounted for. I think there's a risk of this adding so much complexity that it's not worth it.

**Comment by afn** [comment]
Sure - here's how I would approach it. For each index definition, e.g.
```
CREATE INDEX "User ""Email"" Index" ON "Users" USING btree ("Email")
```

we can parse out the possibly-quoted index name (`"User Email"`) and a masked index definition which omits the name (`CREATE INDEX $name ON "Users" USING btree ("Email")`):

```ruby
def parse_index_def(index_def)
  masked_def = index_def.sub(/((?:"(?:[^"]|"")*")|\S+)(?= ON )/, "$name")
  [$1, masked_def] if $1
end
```

Then, for a given table, we can build an index name map, with the key being the masked index definition and the value being the index name, omitting any duplicates:

```ruby
def index_name_map(index_defs)
  parsed = index_defs.map{|index_def| parse_index_def(index_def)}.compact
  parsed.group_by{|r| r[1]}.map{|masked,defs| [masked, defs[0][0]] if defs.length == 1}.compact.to_h
end
```

So now the rename algorithm looks like this:

```ruby
# retired_table_index_defs are the index definitions from the retired table
# table_index_defs are the index definitions from the parent table
orig_index_map = index_name_map(retired_table_index_defs)
intermediate_index_map = index_name_map(table_index_defs)
table_index_defs.each do |index_def|
  masked, name = parse_index_def(index_def)
  intermediate_index_name = intermediate_index_map[masked]
  orig_index_name = orig_index_map[masked]
  if masked && intermediate_index_name && orig_index_name
    rename_index(orig_index_name, retired_index_name) # where retired_index_name is a generated name for this index
    rename_index(intermediate_index_name, orig_index_name)
  elsif !masked
    warn "Couldn't parse index definition: #{index_def}"
  elsif !intermediate_index_name
    warn "Couldn't unambiguously identify index on parent table: #{index_def}"
  elsif !orig_index_name
    warn "Couldn't unambiguously identify index on retired table: #{index_def}"
  end
end
```

The approach for foreign key names would be similar.

I would make this part of the `swap` operation (and have it perform the reverse operation in `unswap`). The worst-case scenario is that it fails to unambiguously determine the index names (or fails to parse an index definition), and as a result, some indexes won't be renamed and the user sees a warning. But since it checks for unambiguity on both tables, it won't perform any renames that it can't revert in `unswap`.

The only lingering question is how to generate the index name `retired_index_name`. The automatic names generated by postgres typically look like `{tablename}_{col1}_{col2...}_idx` but there are some cases where this won't work (e.g. index name is too long, index name is already taken). The simplest workaround would be to just name the index something like `idx_{randomnumber}`. It would be **nice** to have meaningful index names, but probably not worth the trouble, since these generated names would only be used on the retired table (or the intermediate table, if the user rolls back), and not on any tables that are expected to be long-lived.

LMK what you think!

**Comment by ankane** [comment]
Hey @afn, not sure I follow the suggestion. Can you walk through the entire process with an index with the definition:

```sql
CREATE INDEX some_index ON users (email)
```

**Comment by afn** [comment]
Sorry for dropping the ball and not responding sooner...

So let's say you have:

```sql
CREATE TABLE users (id INTEGER, email VARCHAR, created TIMESTAMP, PRIMARY KEY(id));
CREATE INDEX users_email_index ON users (email);
```

Here's the process, step by step:

1. `pgslice prep users created month`: now we have a `users` table with an index named `users_email_index` and a `users_intermediate` table with an index named `users_intermediate_email_idx`.
2. `pgslice add_partitions users --intermediate --past 3 --future 3`: this creates the partition tables, each of which has indexes named like `users_201707_email_idx`
3. `pgslice swap users`: this is where the behavior changes. Currently, the resulting schema has `users_retired` with an index named `users_email_index` and `users` with an index named `users_intermediate_email_idx`. Instead, I'd expect the following SQL to be executed by the `swap` command:
    ```sql
    BEGIN;
    SET LOCAL lock_timeout = '5s';
    ALTER TABLE users RENAME TO users_retired;
    ALTER TABLE users_intermediate RENAME TO users;
    ALTER INDEX users_email_index RENAME TO idx_12345; -- this is new
    ALTER INDEX users_intermediate_email_idx RENAME TO users_email_index; -- this is new
    COMMIT;
    ```
4. `pgslice unswap users`: if we roll back the swap operation, it should rename the indexes here as well:
    ```sql
    BEGIN;
    SET LOCAL lock_timeout = '5s';
    ALTER INDEX users_email_index RENAME TO idx_23456; -- this is new
    ALTER INDEX idx_12345 RENAME TO users_email_index; -- this is new
    ALTER TABLE users RENAME TO users_intermediate;
    ALTER TABLE users_retired RENAME TO users;
    COMMIT;
    ```

LMK if that makes sense. Thanks!

**Comment by ankane** [comment]
Hey @afn, not sure I follow how the index name mapping works in your example. Overall, I'm not sure it's worth the complexity and extra `ALTER` SQL statements.

**Comment by ankane** [comment]
Cleaning up stale issues
